
export const seed = async (knex) => {
  // Deletes ALL existing entries
  await knex('reminder_token_definitions').del();

  const rows = await knex('characters').select('id', 'name');
  const byName = Object.fromEntries(rows.map((r) => [r.name, r.id]));

  const reminders = [
    { characterName: 'Acrobat', text: 'Dead' },
    { characterName: 'Alchemist', text: 'Is The Alchemist' },
    { characterName: 'Al-Hadikhia', text: '1' },
    { characterName: 'Al-Hadikhia', text: '2' },
    { characterName: 'Al-Hadikhia', text: '3' },
    { characterName: 'Amnesiac', text: '?' },
    { characterName: 'Artist', text: 'No Ability' },
    { characterName: 'Assassin', text: 'No Ability' },
    { characterName: 'Assassin', text: 'Dead' },
    { characterName: 'Balloonist', text: 'Seen' },
    { characterName: 'Banshee', text: 'Has Ability' },
    { characterName: 'Barber', text: 'Haircuts Tonight' },
    { characterName: 'Bounty Hunter', text: 'Known' },
    { characterName: 'Butler', text: 'Master' },
    { characterName: 'Cannibal', text: 'Died Today' },
    { characterName: 'Cannibal', text: 'Poisoned' },
    { characterName: 'Cerenovus', text: 'Mad' },
    { characterName: 'Courtier', text: 'Drunk 1' },
    { characterName: 'Courtier', text: 'Drunk 2' },
    { characterName: 'Courtier', text: 'Drunk 3' },
    { characterName: 'Courtier', text: 'No Ability' },
    { characterName: 'Damsel', text: 'Guess Used' },
    { characterName: 'Devil\'s Advocate', text: 'Survives Execution' },
    { characterName: 'Drunk', text: 'Is The Drunk' },
    { characterName: 'Engineer', text: 'No Ability' },
    { characterName: 'Evil Twin', text: 'Twin' },
    { characterName: 'Exorcist', text: 'Chosen' },
    { characterName: 'Fang Gu', text: 'Dead' },
    { characterName: 'Fang Gu', text: 'Once' },
    { characterName: 'Fearmonger', text: 'Fear' },
    { characterName: 'Fisherman', text: 'No Ability' },
    { characterName: 'Flowergirl', text: 'Demon Not Voted' },
    { characterName: 'Flowergirl', text: 'Demon Voted' },
    { characterName: 'Fool', text: 'No Ability' },
    { characterName: 'Fortune Teller', text: 'Red Herring' },
    { characterName: 'Gambler', text: 'Dead' },
    { characterName: 'Goblin', text: 'Claimed' },
    { characterName: 'Godfather', text: 'Dead' },
    { characterName: 'Godfather', text: 'Died Today' },
    { characterName: 'Golem', text: 'May Not Nominate' },
    { characterName: 'Goon', text: 'Drunk' },
    { characterName: 'Gossip', text: 'Dead' },
    { characterName: 'Grandmother', text: 'Dead' },
    { characterName: 'Grandmother', text: 'Grandchild' },
    { characterName: 'Harpy', text: '2nd' },
    { characterName: 'Harpy', text: 'Mad' },
    { characterName: 'Hatter', text: 'Tea Party Tonight' },
    { characterName: 'Huntsman', text: 'No Ability' },
    { characterName: 'Imp', text: 'Dead' },
    { characterName: 'Innkeeper', text: 'Drunk' },
    { characterName: 'Innkeeper', text: 'Safe' },
    { characterName: 'Investigator', text: 'Minion' },
    { characterName: 'Investigator', text: 'Wrong' },
    { characterName: 'Juggler', text: 'Correct' },
    { characterName: 'Kazali', text: 'Dead' },
    { characterName: 'Knight', text: 'Know' },
    { characterName: 'Legion', text: 'About To Die' },
    { characterName: 'Legion', text: 'Die' },
    { characterName: 'Leviathan', text: 'Day 1' },
    { characterName: 'Leviathan', text: 'Day 2' },
    { characterName: 'Leviathan', text: 'Day 3' },
    { characterName: 'Leviathan', text: 'Day 4' },
    { characterName: 'Leviathan', text: 'Day 5' },
    { characterName: 'Leviathan', text: 'Good Player Executed' },
    { characterName: 'Librarian', text: 'Outsider' },
    { characterName: 'Librarian', text: 'Wrong' },
    { characterName: 'Lil\' Monsta', text: 'Dead' },
    { characterName: 'Lil\' Monsta', text: 'Is The Demon' },
    { characterName: 'Lleech', text: 'Dead' },
    { characterName: 'Lleech', text: 'Poisoned' },
    { characterName: 'Lunatic', text: 'Chosen' },
    { characterName: 'Lycanthrope', text: 'Dead' },
    { characterName: 'Marionette', text: 'Is The Marionette' },
    { characterName: 'Mathematician', text: 'Abnormal' },
    { characterName: 'Mezepheles', text: 'No Ability' },
    { characterName: 'Mezepheles', text: 'Turns Evil' },
    { characterName: 'Minstrel', text: 'Everyone Is Drunk' },
    { characterName: 'Monk', text: 'Safe' },
    { characterName: 'Moonchild', text: 'Dead' },
    { characterName: 'Nightwatchman', text: 'No Ability' },
    { characterName: 'Noble', text: 'Know' },
    { characterName: 'No Dashii', text: 'Dead' },
    { characterName: 'No Dashii', text: 'Poisoned' },
    { characterName: 'Ojo', text: 'Dead' },
    { characterName: 'Organ Grinder', text: 'About To Die' },
    { characterName: 'Philosopher', text: 'Drunk' },
    { characterName: 'Philosopher', text: 'Is The Philosopher' },
    { characterName: 'Pixie', text: 'Ability' },
    { characterName: 'Pixie', text: 'Mad' },
    { characterName: 'Plague Doctor', text: 'Storyteller Ability' },
    { characterName: 'Po', text: '3 Attacks' },
    { characterName: 'Po', text: 'Dead' },
    { characterName: 'Poisoner', text: 'Poisoned' },
    { characterName: 'Poppy Grower', text: 'Evil Wakes' },
    { characterName: 'Preacher', text: 'No Ability' },
    { characterName: 'Professor', text: 'No Ability' },
    { characterName: 'Professor', text: 'Alive' },
    { characterName: 'Pukka', text: 'Dead' },
    { characterName: 'Pukka', text: 'Poisoned' },
    { characterName: 'Puzzlemaster', text: 'Drunk' },
    { characterName: 'Puzzlemaster', text: 'Guess Used' },
    { characterName: 'Sailor', text: 'Drunk' },
    { characterName: 'Scarlet Woman', text: 'Is The Demon' },
    { characterName: 'Seamstress', text: 'No Ability' },
    { characterName: 'Shabaloth', text: 'Alive' },
    { characterName: 'Shabaloth', text: 'Dead' },
    { characterName: 'Slayer', text: 'No Ability' },
    { characterName: 'Snake Charmer', text: 'Poisoned' },
    { characterName: 'Steward', text: 'Know' },
    { characterName: 'Summoner', text: 'Night 1' },
    { characterName: 'Summoner', text: 'Night 2' },
    { characterName: 'Summoner', text: 'Night 3' },
    { characterName: 'Sweetheart', text: 'Drunk' },
    { characterName: 'Tea Lady', text: 'Cannot Die' },
    { characterName: 'Tinker', text: 'Dead' },
    { characterName: 'Town Crier', text: 'Minion Nominated' },
    { characterName: 'Town Crier', text: 'Minion Not Nominated' },
    { characterName: 'Undertaker', text: 'Died Today' },
    { characterName: 'Vigormortis', text: 'Has Ability' },
    { characterName: 'Vigormortis', text: 'Dead' },
    { characterName: 'Vigormortis', text: 'Poisoned' },
    { characterName: 'Village Idiot', text: 'Drunk' },
    { characterName: 'Virgin', text: 'No Ability' },
    { characterName: 'Vortox', text: 'Dead' },
    { characterName: 'Washerwoman', text: 'Townsfolk' },
    { characterName: 'Washerwoman', text: 'Wrong' },
    { characterName: 'Widow', text: 'Knows' },
    { characterName: 'Widow', text: 'Poisoned' },
    { characterName: 'Witch', text: 'Cursed' },
    { characterName: 'Yaggababble', text: 'Dead' },
    { characterName: 'Zombuul', text: 'Dead' },
    { characterName: 'Zombuul', text: 'Died Today' },
  ];

  for (const r of reminders) {
    const charId = byName[r.characterName];
    if (!charId) {
      throw new Error(`Unknown character name ${r.characterName}`);
    }
    await knex('reminder_token_definitions').insert({
      character_id: charId,
      text: r.text
    });
  }
};
